package PS3PAD;

import java.util.ArrayList;

public class PS3_PAD {

    //Set of PS3 buttons
    PS3_PADBUTTON BUTTONSELECT = new PS3_PADBUTTON("BUTTONSELECT", 2, -1, (byte) 0x01);
    PS3_PADBUTTON BUTTONLANALOG = new PS3_PADBUTTON("BUTTONLANALOG", 2, -1, -1, (byte) 0x02);
    PS3_PADBUTTON BUTTONRANALOG = new PS3_PADBUTTON("BUTTONRANALOG", 2, -1, -1, (byte) 0x04);
    PS3_PADBUTTON BUTTONSTART = new PS3_PADBUTTON("BUTTONSTART", 2, -1, (byte) 0x08);
    PS3_PADBUTTON BUTTONUP = new PS3_PADBUTTON("BUTTONUP", 2, -1, (byte) 0x10);
    PS3_PADBUTTON BUTTONRIGHT = new PS3_PADBUTTON("BUTTONRIGHT", 2, -1, (byte) 0x20);
    PS3_PADBUTTON BUTTONDOWN = new PS3_PADBUTTON("BUTTONDOWN", 2, -1, (byte) 0x40);
    PS3_PADBUTTON BUTTONLEFT = new PS3_PADBUTTON("BUTTONLEFT", 2, -1, (byte) 0x80);
    PS3_PADBUTTON BUTTONL2 = new PS3_PADBUTTON("BUTTONL2", 3, -1, (byte) 0x01);
    PS3_PADBUTTON BUTTONR2 = new PS3_PADBUTTON("BUTTONR2", 3, -1, -1, (byte) 0x02);
    PS3_PADBUTTON BUTTONL1 = new PS3_PADBUTTON("BUTTONL1", 3, -1, -1, (byte) 0x04);
    PS3_PADBUTTON BUTTONR1 = new PS3_PADBUTTON("BUTTONR1", 3, -1, (byte) 0x08);
    PS3_PADBUTTON BUTTONTRIANGLE = new PS3_PADBUTTON("BUTTONTRIANGLE", 3, -1, (byte) 0x10);
    PS3_PADBUTTON BUTTONCIRCLE = new PS3_PADBUTTON("BUTTONCIRCLE", 3, -1, (byte) 0x20);
    PS3_PADBUTTON BUTTONCROSS = new PS3_PADBUTTON("BUTTONCROSS", 3, -1, (byte) 0x40);
    PS3_PADBUTTON BUTTONSQUARE = new PS3_PADBUTTON("BUTTONSQUARE", 3, -1, (byte) 0x80);
    PS3_PADBUTTON BUTTONPS = new PS3_PADBUTTON("BUTTONPS", 4, -1, (byte) 0x01);

    PS3_PADBUTTON[] arrayOfAllButtons = new PS3_PADBUTTON[]{BUTTONSELECT, BUTTONLANALOG, BUTTONRANALOG, BUTTONSTART, BUTTONUP,
            BUTTONRIGHT, BUTTONDOWN, BUTTONLEFT, BUTTONL2, BUTTONR2, BUTTONL1, BUTTONR1, BUTTONTRIANGLE, BUTTONCIRCLE, BUTTONCROSS,
            BUTTONSQUARE, BUTTONPS};

    public void updateButtonsValue(byte[] incommingByteArray) {
        for (PS3_PADBUTTON Button : arrayOfAllButtons) {
            Button.updateButtonValue(incommingByteArray);
        }
    }
}





